# Generated by Django 6.0.2 on 2026-03-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subtask',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='file', max_length=10),
        ),
    ]
