# Generated by Django 6.0.2 on 2026-03-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_document_title_subtask_completion_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='work_docs/'),
        ),
    ]
