# Generated by Django 6.0.2 on 2026-03-31 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_work_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='management.work'),
        ),
    ]
